export {default as HomePage} from './HomePage';
export {default as LoginPage} from './LoginPage';
export {default as ForgetPassword} from './ForgetPassword';
export {default as LogoutPage} from './LogoutPage';
export {default as RegistrationPage} from './RegistrationPage';
export {default as AboutPage} from './AboutPage';
export {default as ContactPage} from './ContactPage';
export {default as ServicesPage} from './ServicesPage';
export {default as PublicPagesLayout} from './PublicPagesLayout';